[package]
name = "zusischewe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
fs_extra = "1.3.0"
xmltree = "0.10"
