[package]
name = "zusischewe"
version = "3.0.0-alpha.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
fs_extra = "1.3.0"
xmltree = "0.10"
